### ISSUE TITLE
ImportError: cannot import name hough_ellipse  &  ValueError: numpy.dtype has the wrong size, try recompiling??

### ISSUE THREAD

**Issue by andyyuan78** [ryankiros/neural-storyteller#10]
## envy@ub1404:/media/envy/data1t/os_prj/github/neural-storyteller$ pip show numpy

Name: numpy
Version: 1.8.2
Location: /usr/lib/python2.7/dist-packages
Requires: 
## envy@ub1404:/media/envy/data1t/os_prj/github/neural-storyteller$ pip show scipy

Name: scipy
Version: 0.17.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: 
envy@ub1404:/media/envy/data1t/os_prj/github/neural-storyteller$ 

envy@ub1404:/media/envy/data1t/os_prj/github/neural-storyteller$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import generate
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "generate.py", line 8, in <module>
> > >     import skimage.transform
> > >   File "/home/envy/.local/lib/python2.7/site-packages/skimage/transform/**init**.py", line 1, in <module>
> > >     from ._hough_transform import (hough_ellipse, hough_line,
> > >   File "__init__.pxd", line 155, in init skimage.transform._hough_transform (skimage/transform/_hough_transform.c:22288)
> > > ValueError: numpy.dtype has the wrong size, try recompiling
> > > 
> > > import generate
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "generate.py", line 8, in <module>
> > >     import skimage.transform
> > >   File "/home/envy/.local/lib/python2.7/site-packages/skimage/transform/**init**.py", line 1, in <module>
> > >     from ._hough_transform import (hough_ellipse, hough_line,
> > > ImportError: cannot import name hough_ellipse

which

**Comment by andyyuan78** [comment]
numpy update can fix it
