### ISSUE TITLE
Unable to detect GPU

### ISSUE THREAD

**Issue by jss367** [ryankiros/neural-storyteller#13]
I'm having an issue with neural-storyteller or Lasagne seeing my GPU. When I try to import generate, I get the following error:

> > > import generate
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "generate.py", line 22, in <module>
> > >     from lasagne.layers.corrmm import Conv2DMMLayer as ConvLayer
> > >   File "/home/julius/anaconda2/lib/python2.7/site-packages/lasagne/layers/corrmm.py", line 22, in <module>
> > >     "requires GPU support -- see http://lasagne.readthedocs.org/en/"
> > > ImportError: requires GPU support -- see http://lasagne.readthedocs.org/en/latest/user/installation.html#gpu-support

Naturally, I thought there was an issue between Lasagne and my GPU, but when I run 
python -c "from theano.sandbox.cuda.dnn import dnn_available as d; print(d() or d.msg)"

I get the following:

Using gpu device 0: GeForce GTX 960 (CNMeM is disabled)
True

I got this both when I ran lasagne version 0.2.dev1 with theano 0.8.0 and lasagne version 0.1 with theano 0.7.0. Any idea what is going wrong and how to fix it?

**Comment by mongoose54** [comment]
Same problem here. Trying to run the Saliency example in the Recipes. I have CUDNN installed with GPU support of course.

**Comment by quintendewilde** [comment]
Hey I got following errors is this related? 
```
Problem occurred during compilation with the command line below:
/usr/bin/clang++ -dynamiclib -g -march=haswell -target-feature +sse2 -target-feature +cx16 -target-feature -tbm -target-feature -avx512ifma -target-feature -avx512dq -target-feature -fma4 -target-feature -prfchw -target-feature +bmi2 -target-feature -xsavec -target-feature +fsgsbase -target-feature +popcnt -target-feature +aes -target-feature -pcommit -target-feature -xsaves -target-feature -avx512er -target-feature -clwb -target-feature -avx512f -target-feature -pku -target-feature -smap -target-feature +mmx -target-feature -xop -target-feature -rdseed -target-feature +hle -target-feature -sse4a -target-feature -avx512bw -target-feature -clflushopt -target-feature +xsave -target-feature -avx512vl -target-feature +invpcid -target-feature -avx512cd -target-feature +avx -target-feature +rtm -target-feature +fma -target-feature +bmi -target-feature -mwaitx -target-feature +rdrnd -target-feature +sse4.1 -target-feature +sse4.2 -target-feature +avx2 -target-feature +sse -target-feature +lzcnt -target-feature +pclmul -target-feature -prefetchwt1 -target-feature +f16c -target-feature +ssse3 -target-feature -sgx -target-feature +cmov -target-feature -avx512vbmi -target-feature +movbe -target-feature +xsaveopt -target-feature -sha -target-feature -adx -target-feature -avx512pf -target-feature +sse3 -D NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -fPIC -undefined dynamic_lookup -I/Users/quintendewilde/anaconda/lib/python3.6/site-packages/numpy/core/include -I/Users/quintendewilde/anaconda/include/python3.6m -I/Users/quintendewilde/anaconda/lib/python3.6/site-packages/theano/gof -fvisibility=hidden -o /Users/quintendewilde/.theano/compiledir_Darwin-16.6.0-x86_64-i386-64bit-i386-3.6.0-64/lazylinker_ext/lazylinker_ext.so /Users/quintendewilde/.theano/compiledir_Darwin-16.6.0-x86_64-i386-64bit-i386-3.6.0-64/lazylinker_ext/mod.cpp -L/Users/quintendewilde/anaconda/lib
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-tbm'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-fma4'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-prfchw'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-pcommit'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-clwb'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-pku'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-smap'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-rdseed'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-sse4a'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-clflushopt'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-mwaitx'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-prefetchwt1'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-sgx'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-sha'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: no such file or directory: '+sse2'
clang: error: no such file or directory: '+cx16'
clang: error: no such file or directory: '+bmi2'
clang: error: language not recognized: 'savec'
clang: error: no such file or directory: '+fsgsbase'
clang: error: no such file or directory: '+popcnt'
clang: error: no such file or directory: '+aes'
clang: error: language not recognized: 'saves'
clang: error: no such file or directory: '+mmx'
clang: error: language not recognized: 'op'
clang: error: no such file or directory: '+hle'
clang: error: no such file or directory: '+xsave'
clang: error: no such file or directory: '+invpcid'
clang: error: no such file or directory: '+avx'
clang: error: no such file or directory: '+rtm'
clang: error: no such file or directory: '+fma'
clang: error: no such file or directory: '+bmi'
clang: error: no such file or directory: '+rdrnd'
clang: error: no such file or directory: '+sse4.1'
clang: error: no such file or directory: '+sse4.2'
clang: error: no such file or directory: '+avx2'
clang: error: no such file or directory: '+sse'
clang: error: no such file or directory: '+lzcnt'
clang: error: no such file or directory: '+pclmul'
clang: error: no such file or directory: '+f16c'
clang: error: no such file or directory: '+ssse3'
clang: error: no such file or directory: '+cmov'
clang: error: no such file or directory: '+movbe'
clang: error: no such file or directory: '+xsaveopt'
clang: error: no such file or directory: '+sse3'

Traceback (most recent call last):
  File "/Users/quintendewilde/anaconda/lib/python3.6/site-packages/theano/gof/lazylinker_c.py", line 74, in <module>
    raise ImportError()
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/quintendewilde/anaconda/lib/python3.6/site-packages/theano/gof/lazylinker_c.py", line 91, in <module>
    raise ImportError()
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/quintendewilde/anaconda/lib/python3.6/site-packages/theano/__init__.py", line 63, in <module>
    from theano.compile import (
  File "/Users/quintendewilde/anaconda/lib/python3.6/site-packages/theano/compile/__init__.py", line 9, in <module>
    from theano.compile.function_module import *
  File "/Users/quintendewilde/anaconda/lib/python3.6/site-packages/theano/compile/function_module.py", line 22, in <module>
    import theano.compile.mode
  File "/Users/quintendewilde/anaconda/lib/python3.6/site-packages/theano/compile/mode.py", line 12, in <module>
    import theano.gof.vm
  File "/Users/quintendewilde/anaconda/lib/python3.6/site-packages/theano/gof/vm.py", line 638, in <module>
    from . import lazylinker_c
  File "/Users/quintendewilde/anaconda/lib/python3.6/site-packages/theano/gof/lazylinker_c.py", line 126, in <module>
    preargs=args)
  File "/Users/quintendewilde/anaconda/lib/python3.6/site-packages/theano/gof/cmodule.py", line 2196, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: Compilation failed (return status=1): clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-tbm'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-fma4'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-prfchw'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-pcommit'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-clwb'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-pku'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-smap'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-rdseed'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-sse4a'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-clflushopt'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-mwaitx'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-prefetchwt1'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-sgx'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-sha'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: no such file or directory: '+sse2'. clang: error: no such file or directory: '+cx16'. clang: error: no such file or directory: '+bmi2'. clang: error: language not recognized: 'savec'. clang: error: no such file or directory: '+fsgsbase'. clang: error: no such file or directory: '+popcnt'. clang: error: no such file or directory: '+aes'. clang: error: language not recognized: 'saves'. clang: error: no such file or directory: '+mmx'. clang: error: language not recognized: 'op'. clang: error: no such file or directory: '+hle'. clang: error: no such file or directory: '+xsave'. clang: error: no such file or directory: '+invpcid'. clang: error: no such file or directory: '+avx'. clang: error: no such file or directory: '+rtm'. clang: error: no such file or directory: '+fma'. clang: error: no such file or directory: '+bmi'. clang: error: no such file or directory: '+rdrnd'. clang: error: no such file or directory: '+sse4.1'. clang: error: no such file or directory: '+sse4.2'. clang: error: no such file or directory: '+avx2'. clang: error: no such file or directory: '+sse'. clang: error: no such file or directory: '+lzcnt'. clang: error: no such file or directory: '+pclmul'. clang: error: no such file or directory: '+f16c'. clang: error: no such file or directory: '+ssse3'. clang: error: no such file or directory: '+cmov'. clang: error: no such file or directory: '+movbe'. clang: error: no such file or directory: '+xsaveopt'. clang: error: no such file or directory: '+sse3'. 

```
