### ISSUE TITLE
generate story error

### ISSUE THREAD

**Issue by itsss** [ryankiros/neural-storyteller#27]
/ais/gobi3/u/rkiros/storyteller/romance.npz
Loading skip-thoughts...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "generate.py", line 86, in load_all
    config.paths['sktables'])
  File "skipthoughts.py", line 29, in load_model
    with open('%s.pkl'%path_to_umodel, 'rb') as f:
IOError: [Errno 2] No such file or directory: '/u/rkiros/public_html/models/uni_skip.npz.pkl'

import generate
**z = generate.load_all()**
generate.story(z, './images/ex1.jpg')

What should i do???

**Comment by YknZhu** [comment]
The error message indicates you haven't set the model path in config.py. Please download the models as described in README, and update the model path accordingly.
