### ISSUE TITLE
vgg19.pkl link not available

### ISSUE THREAD

**Issue by hashiting** [ryankiros/neural-storyteller#45]
Hi, can anyone please send me the vgg19.pkl file?
leepengqiu@gmail.com

**Comment by LangruiZhou** [comment]
Hi,has anyone sent you the file?I can't open the link,too.Would you like to send me the file if anyone sent it to you?Thank you very much! And my e-mail: depth1024@icloud.com   Thanks again!

**Comment by amereu** [comment]
> Hi,has anyone sent you the file?I can't open the link,too.Would you like to send me the file if anyone sent it to you?Thank you very much! And my e-mail: [depth1024@icloud.com](mailto:depth1024@icloud.com) Thanks again!

Look here
https://github.com/facebookresearch/Detectron/issues/613

**Comment by LangruiZhou** [comment]
It works！Thank you very much！

**Comment by Pjchardt** [comment]
Hi, I used the vgg19.pkl file linked from here, but I am getting an EOFError. 

`Traceback (most recent call last):
  File "test.py", line 4, in <module>
    z = generate.load_all()
  File "C:\Personal\Python\python2\neural_storytelling\neural-storyteller\generate.py", line 108, in load_all
    net = build_convnet(config.paths['vgg'])
  File "C:\Personal\Python\python2\neural_storytelling\neural-storyteller\generate.py", line 220, in build_convnet
    model = pkl.load(open(path_to_vgg))
EOFError`

I have double checked my path several times and it seems correct. @Depth1024 you were able to get the vgg19 file loading running on the gpu? I don't think it is used on the cpu, so my only issue is when trying to run on gpu.

**Comment by ali0517** [comment]
发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Bourne <notifications@github.com>
发送时间: Thursday, August 15, 2019 6:52:56 AM
收件人: ryankiros/neural-storyteller <neural-storyteller@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [ryankiros/neural-storyteller] vgg19.pkl link not available (#45)


It works！Thank you very much！

―

**Comment by occkka** [comment]
> Hi, I used the vgg19.pkl file linked from here, but I am getting an EOFError.
> 
> `Traceback (most recent call last): File "test.py", line 4, in <module> z = generate.load_all() File "C:\Personal\Python\python2\neural_storytelling\neural-storyteller\generate.py", line 108, in load_all net = build_convnet(config.paths['vgg']) File "C:\Personal\Python\python2\neural_storytelling\neural-storyteller\generate.py", line 220, in build_convnet model = pkl.load(open(path_to_vgg)) EOFError`
> 
> I have double checked my path several times and it seems correct. @Depth1024 you were able to get the vgg19 file loading running on the gpu? I don't think it is used on the cpu, so my only issue is when trying to run on gpu.

I got the same problem...If anyone has solved the EOFEroor, please share the method here. 
I am also trying to get the vgg19.pkl file by using aws cli (as [this page](https://github.com/Lasagne/Recipes) says we can download with it!) but don't know how to access the s3 bucket...

**Comment by bamboo06** [comment]
> It works！Thank you very much！

你的这个代码正常运行起来了？
